@startuml

'Описание состояний
state "Начальное_состояние" as state0
state0:entry /
state0: Забл. все ф-и (Ректор, ОСПК, РСПК)
state0: Разбл. ф-и просм. инф по ЕГЭ, напр. подг,
state0:   обр. прогр. и межд. дог-м.  (Ректор, ОСПК)

state "Подготовка_к_ПК" as state1
state1:entry /
state1: Разбл. ф-ю начала ПК (Ректор)
state1: Разбл. ф-и редакт. инф по ЕГЭ, напр. подг,
state1:   обр. прогр. и межд. дог-м.  (ОСПК)

state "Проведение_ПК" as state2
state2:entry /
state2: Забл. ф-ю начала ПК (Ректор)
state2: Разбл. ф-ю завершения ПК (Ректор)
state2: Разбл. ф-ю просм. стат. ПК (Ректор, ОСПК)
state2: Забл. ф-и редакт. инф по ЕГЭ, напр. подг,
state2:   обр. прогр. и межд. дог-м.  (ОСПК)
state2: Разбл. ф-ю блокировки абит. (ОСПК)
state2: Разбл. все ф-и (РСПК)
' do
state2:do /
state2:Ежедн. выводить рейтинг абит.

state "Завершение_ПК" as state3
state3:entry /
state3: Вывести список абит-в, рекоменд. к зачисл.
state3: Забл. ф-ю завершения ПК (Ректор)
state3: Разбл. ф-ю начала подг. к нов. ПК (Ректор)
state3: Забл. ф-ю блокировки абит. (ОСПК)
state3: Забл. все ф-и (РСПК)

'Описание переходов
[*] --> state0
state0 --> state1
state1 --> state2 : Сигнал начала ПК (Ректор)
state2 --> state3 : Сигнал завершения ПК (Ректор)
state3 --> state1 : Сигнал о нач. подг\n к нов. ПК (Ректор)
state3 --> [*] : Решение об отказе\n от дальн. исп-я системы (Ректор)

@enduml
